### ISSUE TITLE
[3.18.1] requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-screens#1614]
### Description

After upgrading to 3.18.1 it throwed:

`Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.`

it seems that the introduction of `react-native-config.js` won't allow the package to be bundled since`metro` throws: 

`warn Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors" is not allowed`

ps. I'm using `yarn 3.2.4`

### Steps to reproduce

1. Install/Upgrade to 3.18.1
2.  pod install
3. build app

### Snack or a link to a repository

no snack

### Screens version

3.18.1

### React Native version

0.68.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by Stackerr** [comment]
same issue 

after  "react-native start --reset-cache" 
i find the warn message below 
Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors

**Comment by efstathiosntonas** [comment]
Since the `react-native-safe-area-context` was [bumped](https://github.com/software-mansion/react-native-screens/blob/a6fc428484bcc797abae4cef39771c0d6e470ad3/FabricTestExample/package.json#L24) to `4.4.1` I think `3.18.1` is no longer supported on react-native < `0.70`

**Comment by n3tflex** [comment]
On my project downgrading to v3.18.0 does not work. Still get the

`Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors" is not allowed` 

message when building the app.

**Comment by efstathiosntonas** [comment]
@n3tflex did you try to run with `--reset-cache`? Removing the `node_modules` prior doing so might help too.

**Comment by Letty** [comment]
@n3tflex Maybe check your `yarn.lock` file for the version there. I often delete the lockfile to make sure to have the needed versions.

**Comment by kkafar** [comment]
Hi all, only change 3.18.1 introduced was to add `react-native.config.js` file which is required for the library to run on new architecture, there were no changes to any dependency versions. 

I'll dive into the problem and let you know asap whats going on

> Since the react-native-safe-area-context was [bumped](https://github.com/software-mansion/react-native-screens/blob/a6fc428484bcc797abae4cef39771c0d6e470ad3/FabricTestExample/package.json#L24) to 4.4.1 I think 3.18.1 is no longer supported on react-native < 0.70.

It was only bumped in `FabricTestExample` application and should have no impact on library usage.

**Comment by efstathiosntonas** [comment]
@kkafar thanks, you're right about the `react-native-safe-area-context` I misread the file name at the diff.

**Comment by efstathiosntonas** [comment]
@n3tflex as a last measure, delete the cache of npm, sorry to ask again since it was not clear on your response, did you run the metro bunder with `--reset-cache` flag?

**Comment by n3tflex** [comment]
Steps I have done:

1. edited `package.json to` `"react-native-screens": "^3.18.0"`
2. deleted `node_modules` & `package-lock.json`
3. deleted `Pods` & `Podfile.lock`
4. `npm cache clean --force  `
5. `npm install`
6. `pod install`
7.  `react-native run-ios --reset-cache`

And I still get same warning. 

Thanks for your help!

**Comment by Letty** [comment]
> Steps I have done:
> 
>     1. edited `package.json to` `"react-native-screens": "^3.18.0"`
> 
>     2. deleted `node_modules` & `package-lock.json`
> 
>     3. deleted `Pods` & `Podfile.lock`
> 
>     4. `npm cache clean --force  `
> 
>     5. `npm install`
> 
>     6. `pod install`
> 
>     7. `react-native run-ios --reset-cache`
> 
> 
> And I still get same warning.
> 
> Thanks for your help!

You have to pin this version
`"react-native-screens": "3.18.0"`

**Comment by kkafar** [comment]
I'm testing fix by my self now, but would appreciate if any of you would confirm, that this resolves the issue: #1615

Install `react-native-screens` as follows in your package.json:

```json
"react-native-screens": "software-mansion/react-native-screens#49cc61e1fa9926a671d32bbb634a2c43c999e122"
```

**Comment by Letty** [comment]
> I'm testing fix by my self now, but would appreciate if any of you would confirm, that this resolves the issue: #1615
> 
> Install `react-native-screens` as follows in your package.json:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens#49cc61e1fa9926a671d32bbb634a2c43c999e122"
> ```

I tried it in my project at it works like charm! Thank you for the quick reaction on this.
(My RN version is 0.68.4)

**Comment by n3tflex** [comment]
> > Steps I have done:
> > ```
> > 1. edited `package.json to` `"react-native-screens": "^3.18.0"`
> > 
> > 2. deleted `node_modules` & `package-lock.json`
> > 
> > 3. deleted `Pods` & `Podfile.lock`
> > 
> > 4. `npm cache clean --force  `
> > 
> > 5. `npm install`
> > 
> > 6. `pod install`
> > 
> > 7. `react-native run-ios --reset-cache`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I still get same warning.
> > Thanks for your help!
> 
> You have to pin this version `"react-native-screens": "3.18.0"`
> 
> In case you are wondering what the signs mean: https://stackoverflow.com/questions/22137778/what-does-mean-in-package-json-versioning

Sorry my fault. After pinning the package the warning ist finally gone! Thanks!

**Comment by kkafar** [comment]
Thank you @Letty! I'll have 3.18.2 released with this patch soon!

**Comment by irfankhanktk** [comment]
I also fixed this issue using "react-native-screens": "3.18.0",

**Comment by ToniNikolaev23** [comment]
Same error with react-native 0.64.3 .. downgrade to 3.18.0 and works :) Waiting for new release 💯

**Comment by kkafar** [comment]
@ToniNikolaev23,
 #1615 (solution to this issue) causes issues with Example applications in the repository so it is holding release for now, but I'm working on it.

**Comment by mikehardy** [comment]
@kkafar no good deed unpunished ;-). Thanks for react-native-screens and we have 3.18.0 until things are sorted. Cheers

**Comment by kkafar** [comment]
3.18.2 is released, the issue should be resolved. 

In case of any problems just tag me here

**Comment by efstathiosntonas** [comment]
Thank you @kkafar !

**Comment by SanjanaTailor** [comment]
> ```json
> software-mansion/react-native-screens#0f684a76276709df927dab116f7addcb9b8c2a6b
> ```

I tried below options but not working for me. 
Package.json
"react-native": "^0.64.1",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "^3.18.0"
But it is not working for me . 
Other solution also I tried which is mentioned below 
Package.json
"react-native": "^0.64.1",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "^3.18.2"
But This is also not working for me. 

Below solution worked like charm. 
"react-native": "^0.64.1",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "software-mansion/react-native-screens#0f684a76276709df927dab116f7addcb9b8c2a6b",

Below solution as well worked like charm
"react-native": "^0.64.1",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "software-mansion/react-native-screens#49cc61e1fa9926a671d32bbb634a2c43c999e122".

@kkafar  - May I know please when the the branch will be committed and which version shall we use to compatible with react-native please.

Thank you.

**Comment by SanjanaTailor** [comment]
> I'm testing fix by my self now, but would appreciate if any of you would confirm, that this resolves the issue: #1615
> 
> Install `react-native-screens` as follows in your package.json:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens#49cc61e1fa9926a671d32bbb634a2c43c999e122"
> ```
> 
> Update: the branch was deleted, before 3.18.2 is released please use current main:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens#0f684a76276709df927dab116f7addcb9b8c2a6b"
> ```

Both are working for me Thank you @kkafar

**Comment by SanjanaTailor** [comment]
> 3.18.2 is released, the issue should be resolved.
> 
> In case of any problems just tag me here

It is not working for me ^3.18.2 is not working.

**Comment by kkafar** [comment]
Hi @SanjanaTailor, 
My first impression is that it is rather strange, as 3.18.2 was cut of exactly this commit: `0f684a76276709df927dab116f7addcb9b8c2a6b`, thus I rather expect that fixing the version to `"3.18.2"` (not `"^3.18.2"`) and running `rm -fr node_modules && yarn install` should resolve the issue.

**Comment by SanjanaTailor** [comment]
> Hi @SanjanaTailor, My first impression is that it is rather strange, as 3.18.2 was cut of exactly this commit: `0f684a76276709df927dab116f7addcb9b8c2a6b`, thus I rather expect that fixing the version to `"3.18.2"` (not `"^3.18.2"`) and running `rm -fr node_modules && yarn install` should resolve the issue.
> 
> I would love you confirmed this, because if it is not the case (id does not work for you on 3.18.2), it implies that there are some additional issues in release configuration.

@kkafar - I think I have tried it but  did not resolve the issue. what can be additional release configuration. Anything required from my end please let me know.

**Comment by SanjanaTailor** [comment]
> Hi @SanjanaTailor, My first impression is that it is rather strange, as 3.18.2 was cut of exactly this commit: `0f684a76276709df927dab116f7addcb9b8c2a6b`, thus I rather expect that fixing the version to `"3.18.2"` (not `"^3.18.2"`) and running `rm -fr node_modules && yarn install` should resolve the issue.
> 
> I would love you confirmed this, because if it is not the case (id does not work for you on 3.18.2), it implies that there are some additional issues in release configuration.

@kkafar - npm ERR! notarget No matching version found for react-native-screens@3.18.2. this issue is happening.

**Comment by Breyner-Parada** [comment]
I have the same problem, these are my dependencies:
"dependencies": {
    "@react-navigation/native": "^6.0.16",
    "@react-navigation/native-stack": "^6.9.4",
    "nativewind": "^2.0.11",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "3.18.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0",
    "tailwindcss": "^3.2.4"
  },

Should I remove the caret sign "^"on every dependency?

**Comment by Breyner-Parada** [comment]
> I have the same problem, these are my dependencies: "dependencies": { "@react-navigation/native": "^6.0.16", "@react-navigation/native-stack": "^6.9.4", "nativewind": "^2.0.11", "react": "18.1.0", "react-native": "0.70.6", "react-native-safe-area-context": "^4.4.1", "react-native-screens": "3.18.0" }, "devDependencies": { "@babel/core": "^7.12.9", "@babel/runtime": "^7.12.5", "@react-native-community/eslint-config": "^2.0.0", "babel-jest": "^26.6.3", "eslint": "^7.32.0", "jest": "^26.6.3", "metro-react-native-babel-preset": "0.72.3", "react-test-renderer": "18.1.0", "tailwindcss": "^3.2.4" },
> 
> Should I remove the caret sign "^"on every dependency I appreciate any info, thanks in advance

I just find other way to solve it

1. Close metro
2. Go into android folder
3. Run in a terminal ".\gradlew clean"
4. Delete the build app on your emulator or physical device
5. Finally run again metro and then run android

Note: I just try it in an android environment and it's worked

**Comment by harishpalsande9** [comment]
i also got it same error but I did it 

**npm i**  then is working fine

and another thing is check internet conection

**Comment by Desintegrator** [comment]
same issue

**Comment by rohitkatare54** [comment]
I'm still facing same error. How to resolve it ?

**Comment by Breyner-Parada** [comment]
For that error
1. Delete both build app folder on android and ios
2. Uninstall the dev app from your phone (android or ios)
 2.1. This step is special for ios verify your cocoapods, package.json and all gems should be installed
 2.2. This step is special or android just verify the package.json 
3. Finally run the commands to install the app on yur phone 

I hope this help you 👍

**Comment by dansau84** [comment]
guys why there´s no any clear fix for this ? it looks like all are trowing stuff against the wall to see if it sticks..  the feature owner should come up with a solution asap!   i´m using expo native react and same error here!

**Comment by ramit-mitra** [comment]
> guys why there´s no any clear fix for this ? it looks like all are trowing stuff against the wall to see if it sticks.. the feature owner should come up with a solution asap! i´m using expo native react and same error here!

Same here!

**Comment by bogdan2510** [comment]
> guys why there´s no any clear fix for this ? it looks like all are trowing stuff against the wall to see if it sticks.. the feature owner should come up with a solution asap! i´m using expo native react and same error here!

'ASAP' is a very hard word. Please remember this is open source work. So people are investing time doing cool stuff mostly for free. :). I'm sure a better word choice goes a long way. Thanks

**Comment by AbdullahAgsar** [comment]
> pod install

npm run ios --reset-cache
 worked for me

**Comment by mianaamirshehzad** [comment]
This error happens while installing react-native-screen & react-native-safe-area-view packages. I suggest installing them one by one rather than with a single command. Also, the possible solution is already mentioned above.  I'm just modifying it as:

- Delete node_modules and package-lock.json file. 
- Run npm cache clean --force. 
- Then move to android folder using **cd android** and run **./gradlew clean**, again jump back to the project folder with **cd ..**
- Install the packages using npm install
- Rebuild your project. 

Hope this will be help you all.

**Comment by moominshera** [comment]
i encountered the same issue ater Editing MainActivity.java file which is located in android/app/src/main/java/<your package name>/MainActivity.java while following [react-navigation-getting-started-guide](https://reactnavigation.org/docs/getting-started)

you need to stop the metro-server

and then, run react-native run-android

**Comment by moominshera** [comment]
I solved this error by changing the version to 3.3.2 and using yarn instead of npm.

Here are the commands I followed:

yarn add nativewind
yarn add --dev tailwindcss@3.3.2

then restart the app

**Comment by Mary-Grigoryan** [comment]
Anyone have other solutions? I have tried **all** of the above steps and nothing has worked for me :( I am doing it on iOS.

Here is my package.json;

{
  "name": "ReactNativeApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-firebase/app": "^18.9.0",
    "@react-native-firebase/auth": "^18.9.0",
    "@react-navigation/native": "^6.1.12",
    "@react-navigation/native-stack": "^6.9.20",
    "firebase": "^10.6.0",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

**Comment by Mary-Grigoryan** [comment]
I fixed this, turned out I was using Native Stack Navigator instead of Stack Navigator which was causing the issue.

**Steps** - also found at https://reactnavigation.org/docs/stack-navigator/#installation:
1. in terminal run `npm install @react-navigation/stack`
2. in terminal run `npm install react-native-gesture-handler`
3. as im using it for iOS -> `cd ios` -> `pod install`

In my AppNavigator.js I changed my import from 
`import { createNativeStackNavigator } from '@react-navigation/native-stack';` to `import { createStackNavigator } from '@react-navigation/stack';`
and my `const Stack = createNativeStackNavigator();` to `const Stack = createStackNavigator();`.

**Comment by Horlard1** [comment]
I fixed this by adding `react-native-screens`

I run the command `npx expo install react-native-screens`

then rebuild the apk using eas

**Comment by tboba** [comment]
Hi @Mary-Grigoryan, I think this is not right solution, as the Stack Navigator does not fully embrace functionalities of react-native-screens (in particular, Stack is not being generated on the native side). 

Have you tried to reset cache of Metro Bundler when this error has occurred (`yarn start --reset-cache` / `npm run start -- --reset-cache`)? Also, is your project using Expo, or it is bare React Native environment?

**Comment by markendy** [comment]
Try DOWNGRADE Node version. In my case, I use RN 0.68.2, and when run app i have this crush "[requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager]" on both platform (android, ios).
I downgrade Node to 16.x (with nvm) and its work. 
If will problem with "yarn" after this, i write answer on strange error in https://stackoverflow.com/a/78107361/22993978

**Comment by Gowtham1802** [comment]
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

This error is located at:
    in RNSScreenStackHeaderConfig (created by HeaderConfig)
    in HeaderConfig (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in FirstApp(RootComponent), js engine: hermes
    
    I am faced this type of error please give me a correct solution for the above error.

**Comment by Mary-Grigoryan** [comment]
> Mary

Hi @tboba, I suspected too that it wouldnt be the right solution. I have changed it back anyway too Native Stack Navigator instead of Stack Navigator. I still have that error anyway.

Also it is a bare React project yes. And i have ran `npm run start -- --reset-cache` and still no fix.

**Comment by kkafar** [comment]
@sujaya-nd I do not know what commit has is this, but definitely try using `react-native-screens@3.32.0` (the most recent one compatible with `react-native@0.71`
