### ISSUE TITLE
Memory Leak. iOS. Strong reference cycle between RNSScreen and RNSScreenView

### ISSUE THREAD

**Issue by mkondakov** [software-mansion/react-native-screens#1754]
### Description

Instance of RNSScreen class creates strong reference cycle with instance of RNSScreenView class. This issue is critical in our project where user can open and close react-native app inside native iOS app many times.

### Steps to reproduce

1. clone project
2. open TestRNSScreens folder in terminal
3. run "pod install"
4. open "TestRNSScreens.xcworkspace" in Xcode
5. run
6. click on "Open RN App" button
7. click on "close" button
8. repeat 6 and 7 steps few times
9. check memory usage in Xcode

### Snack or a link to a repository

https://github.com/mkondakov/RNSScreensMemoryLeak

### Screens version

3.20.0

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Real device

### Device model

all models

### Acknowledgements

Yes

**Comment by ajstokar** [comment]
I believe we are seeing the same issue.  Navigating back and forth between 2 screens causes memory to consistently go up.

**Comment by mkondakov83** [comment]
@kkafar do you have any progress on this issue? We have found that this memory leak is the main reason why application crashes because of low memory conditions. In our app we open and close react-native instances a lot.

**Comment by kkafar** [comment]
Hey, small update from my side. 
I'm investigating the issue but I've not determined root cause of the leak yet unfortunately. 

1. It seems that in standard environment (fully React Native application) there is no leak

<img width="2995" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/50801299/67e15022-c0c8-4fa2-8e8a-140ec558bf67">

You can see in Xcode log console that I've pushed & popped few screens, but in the end there are only two `RNSScreen` controllers allocated -- the first one (for the first screen) and most recent one for the second screen. 

However, at the same time memory usage has risen a bit: 

<img width="601" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/50801299/f7837a44-a67e-43fd-aa5d-1ecfaedfc815">

But as I can detect no apparent leak it nudges me towards conclusion that GC simply was not triggered yet. 


2. I can confirm the leak being present in your reproduction, however it is not clear for me, what change in application setup introduces the key difference here.

Just letting you know that I'm looking, will be back once I have solution.

**Comment by mkondakov** [comment]
@kkafar 
> I can confirm the leak being present in your reproduction, however it is not clear for me, what change in application setup introduces the key difference here.

This memory leak is critical when native iOS app creates multiple instances of react-native applications.
Maybe it is not relevant if you have only 1 instance and navigate inside single react-native app.
But it becomes critical if you close react-native instance.

We have created a temporary workaround. When our ReactAppViewController is closed (it owns RCTRootView) we call invalidate() for all RNSScreenView instances. In other words we destroy all strong-reference connections between RNSScreenView and RNSScreen

<img width="803" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/3126354/4c0d4462-e6c1-42e7-9dfc-fe6bdcb017f1">

**Comment by kkafar** [comment]
Can I get confirmation that this:

* https://github.com/software-mansion/react-native-screens/pull/1797

Fixes the issue in your case?

You can try it out by installing screens from the last commit of that PR:

`package.json`:

```json
"react-native-screens": "software-mansion/react-native-screens#751aab52a043d33e8d13a53de5688e3436a2ef95"
```

**Comment by sunhongda** [comment]
alike

**Comment by sunhongda** [comment]
This problem still exists in version 3.22.1.
demo：https://github.com/OrrHsiao/ReactNativeDemo

**Comment by sunhongda** [comment]
My app is a native app that has infiltrated the RN module. When closing RN and returning to the native module, RTCxxxView cannot trigger the dealloc function . (The RTCxxxViewManage dealloc function will trigger)

**Comment by sunhongda** [comment]
> 这个问题在3.22.1版本中仍然存在。
> 演示：https://github.com/OrrHsiao/ReactNativeDemo

**Comment by mkondakov** [comment]
> Can I get confirmation that this:
> 
> * [fix: memory leak due to retain cycle between view & controller #1797](https://github.com/software-mansion/react-native-screens/pull/1797)
> 
> Fixes the issue in your case?
> 
> You can try it out by installing screens from the last commit of that PR:
> 
> `package.json`:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens#751aab52a043d33e8d13a53de5688e3436a2ef95"
> ```

@kkafar,  looks like your fix works for our case. I have checked your branch:
```json
"react-native-screens": "software-mansion/react-native-screens#@kkafar/retain-cycle-ios"
```

**Comment by sunhongda** [comment]
> 我可以得到确认吗：
> 
> * [修复：由于视图和控制器之间的保留周期导致内存泄漏 #1797](https://github.com/software-mansion/react-native-screens/pull/1797)
> 
> 解决了您的问题吗？
> 
> 您可以通过安装该 PR 上次提交的屏幕来尝试一下：
> 
> `package.json`:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens#751aab52a043d33e8d13a53de5688e3436a2ef95"
> ```

Has the official version been released

**Comment by kkafar** [comment]
Hey,

> Has the official version been released

No, I have not merged it into main branch yet, as the solution I've provided solves this issue, but causes few other ones (e. g. tab navigation crashes). 


The issue here is that while dismissing react native view controller from native side `react-native-screens` components react life-cycle methods do not get triggered - so from library perspective we do not have enough information to determine whether the screen is definitively removed or only temporarily detached from view hierarchy. Thus it looks that the issue arises from buggy interaction between `react-native` and `iOS`. I'll try to see what can be done there.

**Comment by mkondakov** [comment]
@sunhongda, while you are waiting for a fix you may use our workaround: https://github.com/software-mansion/react-native-screens/issues/1754#issuecomment-1604307926
We just braking strong-reference cycle manually on UIViewController deinit. UIViewController is a host for RCTRootView. You just need to have access to RCTBridge.

**Comment by sunhongda** [comment]
> @sunhongda, while you are waiting for a fix you may use our workaround: [#1754 (comment)](https://github.com/software-mansion/react-native-screens/issues/1754#issuecomment-1604307926) We just braking strong-reference cycle manually on UIViewController deinit. UIViewController is a host for RCTRootView. You just need to have access to RCTBridge.

thks

**Comment by sunhongda** [comment]
Android also has similar problems, is there any temporary solution to solve it

**Comment by sunhongda** [comment]
> @sunhongda, while you are waiting for a fix you may use our workaround: https://github.com/software-mansion/react-native-screens/issues/1754#issuecomment-1604307926
> We just braking strong-reference cycle manually on UIViewController deinit. UIViewController is a host for RCTRootView. You just need to have access to RCTBridge.

Android also has similar problems, is there any temporary solution to solve it

**Comment by sunhongda** [comment]
> Hey,
> 
> > Has the official version been released
> 
![img_v2_46e387c4-1621-448a-bde0-c0ce98107f2g](https://github.com/software-mansion/react-native-screens/assets/17448220/872bbffe-bb24-4cff-9dfe-0a8cdfa4a71b)

![img_v2_a8f569c0-f78e-41a2-93ba-fc7d75ef359g](https://github.com/software-mansion/react-native-screens/assets/17448220/dd71b4cc-d3b4-4864-a7d1-9a3fc3e89e12)

> No, I have not merged it into main branch yet, as the solution I've provided solves this issue, but causes few other ones (e. g. tab navigation crashes).
> 
> The issue here is that while dismissing react native view controller from native side `react-native-screens` components react life-cycle methods do not get triggered - so from library perspective we do not have enough information to determine whether the screen is definitively removed or only temporarily detached from view hierarchy. Thus it looks that the issue arises from buggy interaction between `react-native` and `iOS`. I'll try to see what can be done there.

Android leak

**Comment by kkafar** [comment]
Hey, as my PR to React Native is merged I'm closing the issue. I do not know in which RN version it will be first included, but will keep you updated.

https://github.com/facebook/react-native/pull/38617

**Comment by kkafar** [comment]
My patch was just recently picked into RN, and AFAIK it will be available with react-native 
0.73.0-rc.5. However I do not recommend testing it yet, as react-native-screens are not fully compliant with 0.73 yet, and there can be even some build issues. (There is PR in progress to fix that)
