### ISSUE TITLE
armeabi-v7a build error when building react native app

### ISSUE THREAD

**Issue by Madlykeanu** [software-mansion/react-native-screens#2327]
### Description

hello, i get this error when building with ./gradlew assembleRelease.

i was eventually able to fix the error by excluding armeabi-v7a from the react native screens build process but this feels pretty hacky. i was wondering if theres a better solution.

in QuizzifyMobile/node_modules/react-native-screens/android/build.gradle:
```
ndk {
            abiFilters "arm64-v8a", "x86_64" // removed armeabi-v7a as it was causing a build error
            //abiFilters (*res()) // old line
        }
```

i can build my app with ./gradlew assembleDebug and it works fine without excluding armeabi-v7a from react-native-sceens build.gradle

## error:

```
PS C:\Users\ksorc\IdeaProjects\Quizzify\quizzify-mobile-app\quizzifymobile\android> ./gradlew assembleRelease    

> Task :react-native-vector-icons:processReleaseManifest
package="com.oblador.vectoricons" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-vector-icons\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.oblador.vectoricons" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-vector-icons\android\src\main\AndroidManifest.xml.

> Task :react-native-sqlite-storage:processReleaseManifest
package="org.pgsqlite" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-sqlite-storage\platforms\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="org.pgsqlite" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-sqlite-storage\platforms\android\src\main\AndroidManifest.xml.

> Task :react-native-linear-gradient:processReleaseManifest
package="com.BV.LinearGradient" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-linear-gradient\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.BV.LinearGradient" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-linear-gradient\android\src\main\AndroidManifest.xml.

> Task :react-native-community_slider:processReleaseManifest
package="com.reactnativecommunity.slider" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-community\slider\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativecommunity.slider" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-community\slider\android\src\main\AndroidManifest.xml.

> Task :react-native-safe-area-context:processReleaseManifest
package="com.th3rdwave.safeareacontext" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-safe-area-context\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.th3rdwave.safeareacontext" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-safe-area-context\android\src\main\AndroidManifest.xml.

> Task :react-native-async-storage_async-storage:processReleaseManifest 
package="com.reactnativecommunity.asyncstorage" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-async-storage\async-storage\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativecommunity.asyncstorage" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-async-storage\async-storage\android\src\main\AndroidManifest.xml.

> Task :react-native-picker_picker:processReleaseManifest
package="com.reactnativecommunity.picker" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-picker\picker\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativecommunity.picker" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-picker\picker\android\src\main\AndroidManifest.xml.

> Task :react-native-gesture-handler:processReleaseManifest
package="com.swmansion.gesturehandler" found in source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-gesture-handler\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.swmansion.gesturehandler" from the source AndroidManifest.xml: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-gesture-handler\android\src\main\AndroidManifest.xml.

> Task :react-native-vector-icons:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-community_slider:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-community\slider\android\src\oldarch\java\com\reactnativecommunity\slider\ReactSliderManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-async-storage_async-storage:compileReleaseJavaWithJavac
C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java:84: warning: [removal] onCatalystInstanceDestroy() in NativeModule has been deprecated and marked for removal
  public void onCatalystInstanceDestroy() {
              ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\@react-native-async-storage\async-storage\android\src\javaPackage\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :react-native-picker_picker:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:createBundleReleaseJsAndAssets
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
debug Reading Metro config from C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\metro.config.js

> Task :react-native-screens:compileReleaseJavaWithJavac
Note: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-screens\android\src\paper\java\com\swmansion\rnscreens\NativeScreensModuleSpec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:createBundleReleaseJsAndAssets
warning: the transform cache was reset.
                Welcome to Metro v0.80.9
              Fast - Scalable - Integrated



> Task :react-native-safe-area-context:compileReleaseKotlin
w: file:///C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:27:11 'constructor ReactModuleInfo(String!, String!, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. Deprecated in Java
w: file:///C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:33:27 'hasConstants: Boolean' is deprecated. Deprecated in Java
w: file:///C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaView.kt:59:23 'getter for uiImplementation: UIImplementation!' is deprecated. Deprecated in Java     

> Task :react-native-safe-area-context:compileReleaseJavaWithJavac
Note: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-safe-area-context\android\src\paper\java\com\th3rdwave\safeareacontext\NativeSafeAreaContextSpec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gesture-handler:compileReleaseKotlin
w: file:///C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/RNGestureHandlerPackage.kt:69:42 'constructor ReactModuleInfo(String!, String!, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. Deprecated in Java
w: file:///C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/FlingGestureHandler.kt:25:26 Parameter 'event' is never used

> Task :react-native-gesture-handler:compileReleaseJavaWithJavac
Note: C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-gesture-handler\android\paper\src\main\java\com\swmansion\gesturehandler\NativeRNGestureHandlerModuleSpec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-screens:buildCMakeRelWithDebInfo[armeabi-v7a]
C/C++: ninja: error: manifest 'build.ninja' still dirty after 100 tries

> Task :react-native-screens:buildCMakeRelWithDebInfo[armeabi-v7a] FAILED

> Task :app:createBundleReleaseJsAndAssets                              
info Writing bundle output to:, android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle
info Writing sourcemap output to:, android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 7 asset files
info Done copying assets
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:1322:18: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"                            
          typeof DebuggerInternal !== 'undefined' &&
                 ^~~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:6550:7: warning: the variable "setTimeout" was not declared in function "logCapturedError"
      setTimeout(function () {
      ^~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:4660:31: warning: the variable "nativeFabricUIManager" was not declared in anonymous function " 134#"
  var _nativeFabricUIManage = nativeFabricUIManager,
                              ^~~~~~~~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:4688:21: warning: the variable "clearTimeout" was not declared in anonymous function " 134#"
    cancelTimeout = clearTimeout;
                    ^~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:9318:30: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in anonymous function " 134#"
  if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:11738:5: warning: the variable "setImmediate" was not declared in function "handleResolved"
    setImmediate(function () {
    ^~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16010:12: warning: the variable "fetch" was not declared in anonymous function " 373#"
    fetch: fetch,
           ^~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16011:14: warning: the variable "Headers" was not declared in anonymous function " 373#"
    Headers: Headers,
             ^~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16012:14: warning: the variable "Request" was not declared in anonymous function " 373#"
    Request: Request,
             ^~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16013:15: warning: the variable "Response" was not declared in anonymous function " 373#"
    Response: Response
              ^~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16170:24: warning: the variable "FileReader" was not declared in function "readBlobAsArrayBuffer"
      var reader = new FileReader();
                       ^~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16221:36: warning: the variable "Blob" was not declared in anonymous function " 384#"
        } else if (support.blob && Blob.prototype.isPrototypeOf(body)) {
                                   ^~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16223:40: warning: the variable "FormData" was not declared in anonymous function " 384#"
        } else if (support.formData && FormData.prototype.isPrototypeOf(body)) {
                                       ^~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16225:44: warning: the variable "URLSearchParams" was not declared in anonymous function " 384#"
...e if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body...
                                 ^~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16344:26: warning: the variable "AbortController" was not declared in anonymous function " 390#"
          var ctrl = new AbortController();
                         ^~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16478:23: warning: the variable "XMLHttpRequest" was not declared in anonymous function " 394#"
        var xhr = new XMLHttpRequest();
                      ^~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:16023:71: warning: the variable "self" was not declared in anonymous function " 376#"
...undefined' && globalThis || typeof self !== 'undefined' && self ||   
                                      ^~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:26283:27: warning: the variable "performance" was not declared in anonymous function " 689#"
  if ("object" === typeof performance && "function" === typeof performance.no...
                          ^~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:26306:26: warning: the variable "navigator" was not declared in anonymous function " 689#"
  "undefined" !== typeof navigator && undefined !== navigator.scheduling && u...
                         ^~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:26416:37: warning: the variable "MessageChannel" was not declared in anonymous function " 689#"
  };else if ("undefined" !== typeof MessageChannel) {
                                    ^~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:26431:34: warning: the variable "nativeRuntimeScheduler" was not declared in anonymous function " 689#"
... = "undefined" !== typeof nativeRuntimeScheduler ? nativeRuntimeScheduler....
                             ^~~~~~~~~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:35530:34: warning: the variable "requestAnimationFrame" was not declared in function "start 9#"
...    this._animationFrame = requestAnimationFrame(this.onUpdate.bind(this));
                              ^~~~~~~~~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:60349:21: warning: the variable "queueMicrotask" was not declared in anonymous function " 1512#"
  var asap = typeof queueMicrotask !== 'undefined' ? queueMicrotask.bind(_glo...
                    ^~~~~~~~~~~~~~
android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle:60880:76: warning: the variable "Buffer" was not declared in function "convertValue"
... 'function' ? new Blob([value]) : Buffer.from(value);
                                     ^~~~~~

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:buildCMakeRelWithDebInfo[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-screens\android\.cxx\RelWithDebInfo\6t3q1a4x\armeabi-v7a'
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a
  [0/1] Re-running CMake...
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/ksorc/IdeaProjects/Quizzify/Quizzify-mobile-app/QuizzifyMobile/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/6t3q1a4x/armeabi-v7a

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\ksorc\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\Users\\ksorc\\IdeaProjects\\Quizzify\\Quizzify-mobile-app\\QuizzifyMobile\\node_modules\\react-native-screens\\android\\.cxx\\RelWithDebInfo\\6t3q1a4x\\armeabi-v7a" ^
        rnscreens
    from C:\Users\ksorc\IdeaProjects\Quizzify\Quizzify-mobile-app\QuizzifyMobile\node_modules\react-native-screens\android
  ninja: error: manifest 'build.ninja' still dirty after 100 tries      


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.       

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 40s
342 actionable tasks: 279 executed, 63 up-to-date
PS C:\Users\ksorc\IdeaProjects\Quizzify\quizzify-mobile-app\quizzifymobile\android> 
"

my build.gradle in android/app:

"

```

apply plugin: "com.android.application"
apply plugin: "org.jetbrains.kotlin.android"
apply plugin: "com.facebook.react"

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */
react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
    // codegenDir = file("../node_modules/@react-native/codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")

    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]

    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []

    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = true

/**
 * The preferred build flavor of JavaScriptCore (JSC)
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US. Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    compileSdk rootProject.ext.compileSdkVersion

    namespace "com.quizzifymobile"
    defaultConfig {
        applicationId "com.quizzifymobile"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        lightweight {
            //initWith release
            signingConfig signingConfigs.debug
            //debuggable false
        }
    }

}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
"

### Steps to reproduce

1. attempt to build react native app with ./gradlew assemblerelease
2. bug occurs

### Snack or a link to a repository

n/a

### Screens version

3.34.0

### React Native version

0.74.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

windows

### Acknowledgements

Yes

**Comment by Pratik-2102** [comment]
@Madlykeanu did you find any solution for this ?

**Comment by Madlykeanu** [comment]
> @Madlykeanu did you find any solution for this ?
@Pratik-2102 

yes, you can exclude armeabi-v7a from the react-native-screens build proccess in /node_modules/react-native-screens/android/build.gradle:
```
ndk {
            abiFilters "arm64-v8a", "x86_64" // removed armeabi-v7a as it was causing a build error
            //abiFilters (*res()) // old line
        }
 ```

**Comment by ksrajath7** [comment]
Same issue here, the solution provided by @Madlykeanu  seems not helping, any other patches ?

**Comment by alduzy** [comment]
I believe it's a copy of https://github.com/software-mansion/react-native-screens/issues/2082.
Updating to RN 0.75 seems to be fixing this exact problem. Let me know if that's not the case.

**Comment by Pratik-2102** [comment]
@alduzy Problem is fixed

**Comment by pjcape** [comment]
```android\gradle.properties``` :
change ```reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64``` to ```reactNativeArchitectures=arm64-v8a,x86,x86_64```

**Comment by Madlykeanu** [comment]
it is not fixed in the latest update

**Comment by Madlykeanu** [comment]
its not fixed, i still need to exclude armeabi-v7a from reactNativeArchitectures in android\gradle.properties

**Comment by AlexHurPi** [comment]
> `android\gradle.properties`: cambiar `reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64`a`reactNativeArchitectures=arm64-v8a,x86,x86_64`

esto me resolvio el problema, ahora ya puedo generar el APK. muchas gracias
