### ISSUE TITLE
Incorrect form sheet sizing during drag

### ISSUE THREAD

**Issue by nikita-leonov** [software-mansion/react-native-screens#2428]
### Description

The form sheet while being dragged has a glitchy animation as it does not size itself properly to the bottom of the screen.

### Steps to reproduce

1. Run the app from the provided link
2. Press Show Form Sheet
3. Drag the Form Sheet up fast, notice the sizing at the bottom is glitchy. 

Video of the issue:
https://github.com/user-attachments/assets/60052cd9-5448-492b-a2e5-47864a308b54

### Snack or a link to a repository

https://github.com/nikita-leonov/react-native-screens-form-sheet-bug

### Screens version

3.34.0

### React Native version

0.74.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @nikita-leonov, thanks for reporting this issue.

I believe it is already solved with #2045. 

You can try these changes out with latest react-native-screens version 4.0.0-beta.13. 

If this is not the case let us know here, I'll reopen.

**Comment by nikita-leonov** [comment]
@kkafar what would be the right way to test react-native-screens given the project depends on navigation, native stacks, etc? As of now I just forced resolution through yarn to the latest beta. I could still reproduce this issue with blinking despite using beta 13. I updated the example project with beta 13 too.

**Comment by kkafar** [comment]
@nikita-leonov you need [latest rc of `react-navigation@v7`](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fnative-stack%407.0.0-rc.28) and latest beta of screens. 

You will most likely experience sheets content being truncated (but not flickering) - you can workaround that with `unstable_screenStyle: { backgroundColor: <color of your's sheet contents> }`

**Comment by kkafar** [comment]
AFAIK react navigation team wants to port changes from `react-native-screens@v4` to `react-navigation@v6`, however this won't happen before we both release stable versions 4 and 7 respectively.

**Comment by nikita-leonov** [comment]
Thanks for clarifying. I think content truncated and flickering would be equal types of issues for the functionality I have in hand. Is there a ticket to follow regarding the truncation you mentioned above?

**Comment by erickreutz** [comment]
@kkafar any idea on when unstable_sheetFooter might be introduced on iOS?
