### ISSUE TITLE
Cannot remove child at index X from parent ViewGroup X, only X children in parent. Warning: childCount may be incorrect!

### ISSUE THREAD

**Issue by maciekBudzinski** [software-mansion/react-native-screens#2491]
### Description

[Android Only] Application crashes when unmounting a screen with `removeClippedSubviews` set to `true`.

### Steps to reproduce

Run application from reproduction repository (`rnscreens` branch).
Press login, then logout, see the application crash:

[rnscreens_demo.webm](https://github.com/user-attachments/assets/dcc3b3ba-bb06-460b-a3ec-ce9722b77e37)

### Snack or a link to a repository

https://github.com/maciekBudzinski/rnp-material-bottom-tabs-repro-issue/tree/rnscreens

### Screens version

4.0.0

### React Native version

0.76.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by alduzy** [comment]
@maciekBudzinski Thanks for reporting and providing a reproducible code! I opened a PR that aims to fix the problem.

**Comment by marcio-b** [comment]
@alduzy Hey! thank you for addressing this! I was wondering if that PR triggers a new release and if not, what version of the library should we get to have this fix you pushed?

**Comment by kkafar** [comment]
Hey, I'll release version on Monday / Tuesday at latest

**Comment by marcio-b** [comment]
I just wanted to confirm that issue is resolved in v4.2.0.

**Comment by kkafar** [comment]
Thanks a lot @marcio-b!

**Comment by maciekBudzinski** [comment]
Thanks 🎉

**Comment by priyanshubuddy** [comment]
i am using "react-native": "^0.76.7", and "react-native-screens": "^4.9.1" , getting the same issue while back press or with navigation, i tried different versions , still facing the same, can anyone help me ?

**Comment by yuezonglun** [comment]
> i am using "react-native": "^0.76.7", and "react-native-screens": "^4.9.1" , getting the same issue while back press or with navigation, i tried different versions , still facing the same, can anyone help me ?

me to

**Comment by kkafar** [comment]
Please see the library compatibility table [link](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#support-for-fabric).

I've fixed this issue in `react-native` with https://github.com/facebook/react-native/pull/47634 & it should be fixed with `react-native@0.77`.

**Comment by yuezonglun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ashik0019** [comment]
> i am using "react-native": "^0.76.7", and "react-native-screens": "^4.9.1" , getting the same issue while back press or with navigation, i tried different versions , still facing the same, can anyone help me ?

also getting same issue.

**Comment by alithecoder01** [comment]
Hey guys, 
I'm facing the same issue today

**Comment by vtech18** [comment]
> Hey guys, I'm facing the same issue today
> 
> Update I solved it using this: [@ashik0019](https://github.com/ashik0019) [#2339 (comment)](https://github.com/software-mansion/react-native-screens/issues/2339#issuecomment-2727036996)

@kkafar  said it is fixed in 0.77?. Why don't you try

**Comment by jamilAbbas** [comment]
> > i am using "react-native": "^0.76.7", and "react-native-screens": "^4.9.1" , getting the same issue while back press or with navigation, i tried different versions , still facing the same, can anyone help me ?
> 
> also getting same issue.

Getting the same issue, tried all above solutions. I am using     "react-native": "0.76.7",     "react-native-screens": "^4.6.0",

**Comment by kkafar** [comment]
I'll reiterate one last time:

The issue was fixed with `react-native@0.77`. The proper and most straightforward solution is to migrate to 0.77 or newer react-native version. 

@Dosbodoke summarised the situation pretty nicely [here](https://github.com/software-mansion/react-native-screens/issues/2339#issuecomment-2660636324).

I'm closing the thread, as I don't think it requires any more information.
