### ISSUE TITLE
Enabling fullscreenGestures or custom animations can cause content shifts when navigating from a screen without a header to one with a header.

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-screens#2550]
### Description

I discovered a bug that occurs when navigating from a page without a header to a page with a header. The content shifts upward. This issue is reproducible with `fullscreenGestureEnabled` or any other custom animation. 

The problem is likely caused by this PR:  
https://github.com/software-mansion/react-native-screens/pull/2477  

The following Snack isolates this bug to `react-native-screens`. I created two reproductions using `react-navigation` v7 and `expo-router`. Additionally, @satya164 created one using `react-native-screens` directly:  

https://snack.expo.dev/@hirbod/react-native-screens-full-screen-swipe-bug  

I suspect the changes in the header animation are the cause.  

https://github.com/user-attachments/assets/3169da42-13dd-4966-8bcb-4b2f46a00896

## Very likely related
#2536
#2548 

#### Maybe related
https://github.com/expo/expo/issues/33008

### Steps to reproduce

Navigate to the screen with a header, and touch / move it. Swipe back to the screen before and now navigate to that screen again.

Bug does not happen in v3

### Snack or a link to a repository

https://snack.expo.dev/@hirbod/react-native-screens-full-screen-swipe-bug

### Screens version

4.3.0

### React Native version

0.76+

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey! Looks reproducible. Thanks for reporting!

**Comment by hirbod** [comment]
@kkafar I wanna also add two more things, as all of these issues appeared with said #2477

1) `animation` set to `none` does not work anymore. It fades instead when set to none
2) animationMatchesGesture together with fade (and the forced fade lol) is very jittery

In my video, animation is set to none and it turns it into a fade. And when I add animationMatchesGesture, it goes wild

https://github.com/user-attachments/assets/ddf11a7a-caac-4184-8cbe-3c91d26546b3

**Comment by kkafar** [comment]
Hey @hirbod , #2563 should fix this (unfortunately bringing back old header animation, however we'll try to improve this). I've released 4.4.0-rc.0 (available on NPM) - if you have capacity to test this please let me know whether it also works for you or I've still overlooked some case.

**Comment by hirbod** [comment]
I'll check it in about 3 hours, once I am back at the desk. This only addresses the header, not the second message of this issue report regarding the broken animation, right?

**Comment by kkafar** [comment]
animation none will be fixed here: #2565 
as of the "jitter" - I haven't looked into it yet - but if I can reproduce it - there will be separate PR.

**Comment by hirbod** [comment]
rc0 does fix the jump, but the header animation is broken compared to v3. For me, this doesn’t solve the problem; it’s still a regression and not shippable. The only acceptable solution is to fully revert https://github.com/software-mansion/react-native-screens/pull/2477 and release once everything is stable. Right now, it’s just patching with band-aids.

https://github.com/user-attachments/assets/d49b12aa-a9ac-48f0-86ef-436ed9775b6a

**Comment by hirbod** [comment]
Compared to v3 it looks worse because it's a lot slower and much more visible of the timing I guess

https://github.com/user-attachments/assets/eb172ac7-0e39-4064-a12c-0ead9b7a24f9

**Comment by kmagiera** [comment]
@hirbod is this last recording from v3?

**Comment by hirbod** [comment]
@kmagiera v4, but I know the timing curve very well, and the v3 header didn’t crossfade so slowly, which makes the bug more obvious since v4. Either way, the jumping is definitely much worse than this weird-looking header animation, gladly this is gone since rc-0, I hope we can get a decent looking header animation soon

**Comment by matinzd** [comment]
I am bit confused now. Do we have a different issue now? :))

**Comment by kkafar** [comment]
Regarding the animation jitter you reported here: https://github.com/software-mansion/react-native-screens/issues/2550#issuecomment-2520147359 - it seems that it also has been fixed with #2565. The `animationMatchesGesture` + `animation: none` looks bad between screens with header and no header, but it seems that there is no difference between v3 & v4 behaviour and this needs to be fixed separately. 

Otherwise we now have "fade" transition on gesture. 

https://github.com/user-attachments/assets/a100e4ef-71bf-4341-8063-ee6c3debce67

**Comment by hirbod** [comment]
Yes, that looks good. Agree that the Header is a separate issue.
