### ISSUE TITLE
[SDK 52] Crash on Android when using presentation: 'formSheet' and switching apps

### ISSUE THREAD

**Issue by qretsar** [software-mansion/react-native-screens#2627]
### Description

I encountered an issue in Expo SDK 52 while using the presentation: 'formSheet' option in a stack screen. It works perfectly fine on both iOS and Android, except on Android when you:

Open the formSheet.
Switch to another app or access the task manager (e.g., swipe up to view all running apps) while the sheet is opened.
Return to the app.
The app crashes with the following error:

> java.lang.IllegalStateException: Fragment already added: ScreenStackFragment{f1ecdea} (397f0ecd-ef24-42e1-8613-efd2d1e087c3 id=0xa)
  androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:93)
  androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1503)
  androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
  androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2009)
  androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1895)
  androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
  androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
  androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
  androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
  androidx.fragment.app.Fragment.performStart(Fragment.java:3196)
  androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
  androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
  androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
  androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
  androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
  androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
  androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
  androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
  androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
  android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
  android.app.Activity.performStart(Activity.java:8270)
  android.app.ActivityThread.handleStartActivity(ActivityThread.java:3760)
  android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
  android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
  android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:183)
  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:132)
  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:2260)
  android.os.Handler.dispatchMessage(Handler.java:106)
  android.os.Looper.loopOnce(Looper.java:210)
  android.os.Looper.loop(Looper.java:299)
  android.app.ActivityThread.main(ActivityThread.java:8108)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045

> 

> 

This issue occurs in Expo Go, development builds, and release builds, meaning it's not just a development-related bug.

In Expo Go, the error message is not descriptive—making debugging difficult.

In a development or release build, the crash logs indicate:
`java.lang.IllegalStateException: Fragment already added: ScreenStackFragment{f1ecdea}
`

### Steps to reproduce

1. Use a stack navigator in React Navigation.
2. Add a screen with presentation: 'formSheet' as part of the stack.
3. Open the screen on Android.
4. Switch to another app using the task manager.
5. Return to the app.

### Snack or a link to a repository

https://github.com/qretsar/screens-reproduction

### Screens version

4.4.0

### React Native version

0.76.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

Xiaomi 12 (Android 12), Emulator, and others

### Acknowledgements

Yes

**Comment by bhavyavishnani** [comment]
Did you found the solution?
same happening with me!!

**Comment by kkafar** [comment]
Thanks for the report. We'll look into this.

**Comment by christianbach** [comment]
We are also seeing this in our app. We reverted to only showing `formSheet` for iOS and a custom "bottom-sheet" for android. Seeing this in the emulator and real device.

**Comment by hamdij0maa** [comment]
+1

**Comment by kkafar** [comment]
I just wanna update that I'm looking into the issue. However current approach is to forbid certain kinds of navigation patters as they do not make much sense on stack-based navigator. I'm building the case 😅

**Comment by kkafar** [comment]
This should be fixed with 4.7.0-beta.1 

You can test by installing [it](https://github.com/software-mansion/react-native-screens/releases/tag/4.7.0-beta.1) or you should [4.7.0-beta.2](https://github.com/software-mansion/react-native-screens/releases/tag/4.7.0-beta.2) which is closer to stable.

Let me know in case these don't help and the issue still exists (from my testing it looks like it is fixed).

**Comment by RohovDmytro** [comment]
4.7.0-beta.3 fixes the issue for me.

**Comment by RohovDmytro** [comment]
I've noticed a different issues. Just after upgrading from 4.6.0 to beta-3 4.7.0 the crash did disappear, but now the app is crashing if I'm using different kind of a presentation (`containedTransparentModal`) value:

<img width="843" alt="Image" src="https://github.com/user-attachments/assets/9e153087-ba9f-47a6-90b7-3c8fb4c77438" />

**Comment by kkafar** [comment]
@RohovDmytro that stack trace looks interesting. If you happen to have reproduction, please file a new issue.

**Comment by christianbach** [comment]
I just upgrade to the new version `4.7.0` and the error is still present with the same stack trace:

```
02-19 10:13:03.236 24928 24928 E AndroidRuntime: java.lang.IllegalStateException: Fragment already added: ScreenStackFragment{ff03cc2} (ba388e52-5326-4b46-a2f6-0b37fe7ad1d3 id=0x1)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:93)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1503)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2009)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1895)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3196)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3196)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1701)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:9023)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4072)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:270)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:250)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:232)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:170)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2635)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8699)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
02-19 10:13:03.236 24928 24928 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by christianbach** [comment]
I can confirm that this no longer happens in `4.7.0` 🎉
