### ISSUE TITLE
🐛 [Android] 16KB Page Size Compatibility Issue

### ISSUE THREAD

**Issue by amanchd16** [software-mansion/react-native-screens#2996]
### Description

Summary
The native libraries (librnscreens.so and libreact_codegen_rnscreens.so) in react-native-screens are not compatible with Android's 16KB page size requirement, causing Google Play Store warnings and potential crashes on devices with 16KB page sizes.
Environment

react-native-screens version: 4.11.1
React Native version: 0.80.0
Platform: Android
Architecture affected: armeabi-v7a, x86 (32-bit architectures)
Architecture working: arm64-v8a, x86_64 (64-bit architectures)

Description
Google Play Store now warns about apps that are not compatible with 16KB page sizes. Our analysis shows that react-native-screens native libraries have alignment issues on 32-bit architectures:

❌ Problem architectures:
armeabi-v7a/librnscreens.so - Aligned to 0x4 (4KB)
armeabi-v7a/libreact_codegen_rnscreens.so - Aligned to 0x4 (4KB)
x86/librnscreens.so - Aligned to 0x4 (4KB)
x86/libreact_codegen_rnscreens.so - Aligned to 0x4 (4KB)

✅ Working architectures:
arm64-v8a/librnscreens.so - Aligned to 0x4000 (16KB)
arm64-v8a/libreact_codegen_rnscreens.so - Aligned to 0x4000 (16KB)
x86_64/librnscreens.so - Aligned to 0x4000 (16KB)
x86_64/libreact_codegen_rnscreens.so - Aligned to 0x4000 (16KB)

### Steps to reproduce

**Reproducer**: RNTesterPlayground.js is not applicable for this issue.

This is a **native library build configuration issue**, not a JavaScript runtime issue. The problem exists in how React Native's native libraries (.so files) are compiled and linked by the NDK build system.

**To reproduce the actual issue:**
1. Build any React Native Android app
2. Extract the APK: `unzip app-release.apk -d extracted/`
3. Analyze native libraries: `objdump -x extracted/lib/armeabi-v7a/libreactnative.so | grep Align`
4. Observe 4KB alignment (0x4) instead of required 16KB alignment (0x4000)

**JavaScript code cannot reproduce this** because it's a compilation/linking issue that affects the ELF binary format of native libraries, not runtime behavior.

### Snack or a link to a repository

https://developer.android.com/guide/practices/page-sizes

### Screens version

4.11.1

### React Native version

0.80.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by amanchd16** [comment]
**Reproducer**: RNTesterPlayground.js is not applicable for this issue.

This is a **native library build configuration issue**, not a JavaScript runtime issue. The problem exists in how React Native's native libraries (.so files) are compiled and linked by the NDK build system.

**To reproduce the actual issue:**
1. Build any React Native Android app
2. Extract the APK: `unzip app-release.apk -d extracted/`
3. Analyze native libraries: `objdump -x extracted/lib/armeabi-v7a/libreactnative.so | grep Align`
4. Observe 4KB alignment (0x4) instead of required 16KB alignment (0x4000)

**JavaScript code cannot reproduce this** because it's a compilation/linking issue that affects the ELF binary format of native libraries, not runtime behavior.

**Comment by steven-sh** [comment]
Note that the requirements state "devices must support 16 KB page sizes **on 64-bit devices**" so I believe the two 32-bit architectures are fine to have 4KB alignment https://developer.android.com/guide/practices/page-sizes

**Comment by kkafar** [comment]
Yeah, thanks @steven-sh, [this is directly stated here in the first paragraph](https://developer.android.com/guide/practices/page-sizes). 

You're welcome to open a PR with support for 16KB page sizes on the platforms you indicated & we'll land it. However I won't put this on our task board, since it is not required.

**Comment by dprevost-LMI** [comment]
@kkafar @steven-sh, I'm working on supporting 16Kb for store compliance, and when I build my application in Android Studio, I have the below warning. That makes me believe that having `librnscreens.so` on 16Kb is a requirement starting November 1st, 2025.

Note: We encountered five other issues with `.so` dependencies, which were resolved by upgrading the library versions. `rn-screen` is the last one! Can you advise please? Thanks!

```
APK [MASKED] is not compatible with 16 KB devices. Some libraries have LOAD segments not aligned at 16 KB boundaries:
lib/arm64-v8a/librnscreens.so
Starting November 1st, 2025, all new apps and updates to existing apps submitted to Google Play and targeting Android 15+ devices must support 16 KB page sizes. For more information about compatibility with 16 KB devices, visit developer.android.com/16kb-page-size.
```

The five other `.so` warnings that have already been solved:
```
base/lib/arm64-v8a/libpdfiumandroid.so
base/lib/arm64-v8a/libreanimated.so
base/lib/arm64-v8a/libsentry-android.so
base/lib/arm64-v8a/libsentry.so
base/lib/arm64-v8a/libworklets.so
```

**Comment by steven-sh** [comment]
@dprevost-LMI I believe librnscreens.so is shipped as source from NPM and is compiled as part of your app's build process (you'll find the source files in node_modules/react-native-screens/android/src/main/jni).  To build an APK or bundle that's fully compatible with 16kb page size devices you might want to upgrade the version of NDK you're using (version 29 is best but 27 will also work).  I'm using react native screens 3.33.0 and so I needed to patch node_modules/react-native-screens/android/build.gradle.  Replace

```
externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared",
                        "-DRNS_NEW_ARCH_ENABLED=${IS_NEW_ARCHITECTURE_ENABLED}"
            }
        }
```

with

```
externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared",
                        "-DRNS_NEW_ARCH_ENABLED=${IS_NEW_ARCHITECTURE_ENABLED}",
                        "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
            }
        }
```

Also note that for your apk/bundle to work properly you'll need to either compress your .so files in your apk/bundle, or upgrade your build to use the android gradle plugin 8.5.1 or later.  This is because uncompressed .so files need to be aligned to 16kb boundaries in the apk/bundle file and earlier versions of the plugin don't support this.  You only need to do this if you're using uncompressed .so files - you can tell in android studio if you use the apk analyzer - there's a column telling you if a library is compressed or not.

**Comment by dprevost-LMI** [comment]
Thanks @steven-sh, it works. After that, I dug and found [this PR](https://github.com/software-mansion/react-native-screens/pull/2702) available in [4.8.0](https://github.com/software-mansion/react-native-screens/releases/tag/4.8.0). I will upgrade and see!

**Comment by anniewey** [comment]
@steven-sh i applied the patch you suggested but still getting 16kb not supported in google play. any step that i missed out here?

react-native-screens = 3.36.0
ndkVersion = "27.1.12297006"
AGP = 8.7.2
newArchEnabled = false
 
```
Libraries that do not support 16 KB:
base/lib/arm64-v8a/librnscreens.so
base/lib/x86_64/librnscreens.so
```

```
//react-native-screens+3.36.0.patch
diff --git a/node_modules/react-native-screens/android/build.gradle b/node_modules/react-native-screens/android/build.gradle
index 5bcd991..9061c52 100644
--- a/node_modules/react-native-screens/android/build.gradle
+++ b/node_modules/react-native-screens/android/build.gradle
@@ -83,6 +83,7 @@ android {
             cmake {
                 arguments "-DANDROID_STL=c++_shared",
                         "-DRNS_NEW_ARCH_ENABLED=${IS_NEW_ARCHITECTURE_ENABLED}"
+                        "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
             }
         }
     }

```

**Comment by kkafar** [comment]
@anniewey, try using ndkVersion >= 28 [link](https://developer.android.com/guide/practices/page-sizes#build)

**Comment by anniewey** [comment]
@kkafar using `ndkVersion = "28.0.13004108"` resolve it, thanks lot! 🙏

**Comment by gani419** [comment]
@kkafar updating ndk version to 28 solved the issue. Thanks...
