### ISSUE TITLE
Header Height jumps with nested navigators

### ISSUE THREAD

**Issue by dotconnor** [software-mansion/react-native-screens#619]
When you have a nested navigators like this: `NativeStack -> BottomTabs -> NativeStack`, it creates issues when rendering the header from the innermost NativeStack. Only appears to happen when there some other navigator anywhere between two NativeStack ones. For example `Stack -> BottomTabs -> NativeStack` works correctly and `NativeStack -> NativeStack` work correctly.

This seems to be the same bug as #540.

https://github.com/dotconnor/ScreensHeader

## Expected

![Kapture 2020-08-30 at 05 47 11](https://user-images.githubusercontent.com/14323370/91656166-8d929d00-ea84-11ea-8264-bf9776ee003c.gif)

## Actual

![Kapture 2020-08-30 at 05 49 15](https://user-images.githubusercontent.com/14323370/91656176-a438f400-ea84-11ea-8967-c360452414cb.gif)

**Comment by WoLewicki** [comment]
Looks like it is the same issue as https://github.com/software-mansion/react-native-screens/issues/564. Am I right?

**Comment by dotconnor** [comment]
Just tested this, and the issue still happens regardless of the `View` inside the screen, secondly it also happens regardless if the translucent header option is set or not.

**Comment by WoLewicki** [comment]
There seem to be some layout issues when having a `UIViewController` (from `ScreenContainer` of `bottom-tabs`) between 2 `UINavigationController`s (from `ScreenStack` of `native-stack`). As a workaround, you can make the top navigator a normal `stack` (since you don't use any of the `native-stack` specific options, right?).

**Comment by ArekChr** [comment]
> There seem to be some layout issues when having a `UIViewController` (from `ScreenContainer` of `bottom-tabs`) between 2 `UINavigationController`s (from `ScreenStack` of `native-stack`). As a workaround, you can make the top navigator a normal `stack` (since you don't use any of the `native-stack` specific options, right?).

I'm using large and blurred headers from native-stack

**Comment by WoLewicki** [comment]
@ArekChr It is not a solution to the bug, but a workaround, and I know it is wanted for many cases.

**Comment by burakgormek** [comment]
@WoLewicki Any update? I have same issue. I just noticed that this is only happens if stack has animation.
stackAnimation 'none' works without an issue.

simplified test: https://snack.expo.io/KrD6WIJ2l (looks like iOS only)

**Comment by WoLewicki** [comment]
@burakgormek @ArekChr @dotconnor can you check if #1025 fixes the issue and does not introduce any new layout issues? I described the scenario where it won't work, but hopefully it is not common enough nesting pattern.

**Comment by burakgormek** [comment]
@WoLewicki 
Thanks for the PR.

I've tested with the PR and it fixes header jump but only for vertical. Horizontal jumps looks still there. 
simplified test: https://snack.expo.dev/IYo_xZr5a

Not know if this is another issue or not connected this issue though.
 
```
Container
    Screen: Content
    Screen: SecondStack // Causing the problem. Works normally without this stack.
            Screen: Bottom Tab
                Screen: ChildStack > Content
```

With **SecondStack**:

![screen1](https://user-images.githubusercontent.com/7578884/126715162-9c92b925-a8d8-4e75-89ae-339906bbcfe5.jpg)

Without **SecondStack**:

![screen2](https://user-images.githubusercontent.com/7578884/126715205-a4f13718-0990-4bab-9cdc-8fbd61d32356.jpg)

Screenshots saved before the navigate transition end.

With PR vertical jumps gone but horizontal still there:

https://user-images.githubusercontent.com/7578884/126715712-5fb11726-7848-4756-8af6-a8cd9852322e.mp4

**Comment by WoLewicki** [comment]
@burakgormek I tested the snack you provided and it seems that unfortunately it is a different problem than the one fixed by the PR and will not be easy to resolve. Could you submit another issue with suitable description and this reproduction and we will close this one as #1025 is merged?

**Comment by WoLewicki** [comment]
I came up with another option of how to resolve these issues, which is making `ScreenContainer` a `UINavigationController` for `bottom-tabs` and `drawer` (#1025). It is not easy/possible for `stack` navigator. Can you check if it resolves your issues and does not introduce new ones? It requires applying PR from `react-navigation` for it to work: https://github.com/react-navigation/react-navigation/pull/9772.

**Comment by burakgormek** [comment]
@WoLewicki 
I tested the latest PR and can confirm that it works perfect! Thanks.
Also I didn't see any layout issues on my app.

Final result:

https://user-images.githubusercontent.com/7578884/127366457-a20d5d15-9689-433c-8c81-4451bf4d2ce9.mp4

**Comment by WoLewicki** [comment]
Yeah, I meant #1029, sorry. 😅

**Comment by swrobel** [comment]
I have the same issue demonstrated in the original post on this issue when using nested native stack navigators. I tested both of the following:
* #1025 - fixed my issue with jumping
* #1029 - did not fix my issue with jumping

**Comment by WoLewicki** [comment]
@swrobel can you post a reproduction where #1029 does not fix the jumping issue?

**Comment by SimpleCreations** [comment]
@WoLewicki I'll throw in my two cents. I have the same issue with a native stack navigator nested in a tab navigator nested in another native stack navigator.
I have the same results as @swrobel - #1025 fixes the issue but #1029 doesn't. Here's the repro.

```typescript
import React from "react";
import { Button, SafeAreaView } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator, NativeStackScreenProps } from "react-native-screens/native-stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

const RootStack = createNativeStackNavigator();
const BottomTabs = createBottomTabNavigator();
const ChildStack = createNativeStackNavigator();

type RootStackParamsList = {
  BottomTabsScreen: undefined;
};

const HomeScreen = ({navigation}: NativeStackScreenProps<RootStackParamsList>) => (
  <SafeAreaView>
    <Button
      title="Navigate to BottomTabsScreen"
      onPress={() => navigation.navigate("BottomTabsScreen")} />
  </SafeAreaView>
);

const BottomTabsScreen = () => (
  <BottomTabs.Navigator
    initialRouteName="FirstBottomTabScreen"
    screenOptions={{headerShown: false}}>
    <BottomTabs.Screen
      name="FirstBottomTabScreen"
      component={FirstBottomTabScreen} />
  </BottomTabs.Navigator>
);

const FirstBottomTabScreen = () => (
  <ChildStack.Navigator
    initialRouteName="ChildStackScreen">
    <ChildStack.Screen
      name="ChildStackScreen"
      component={ChildStackScreen} />
  </ChildStack.Navigator>
);

const ChildStackScreen = () => null;

const App = () => (
  <NavigationContainer>
    <RootStack.Navigator
      initialRouteName="HomeScreen"
      screenOptions={{headerShown: false}}>
      <RootStack.Screen
        name="HomeScreen"
        component={HomeScreen} />
      <RootStack.Screen
        name="BottomTabsScreen"
        component={BottomTabsScreen} />
    </RootStack.Navigator>
  </NavigationContainer>
);

export default App;
```

**Comment by burakgormek** [comment]
@SimpleCreations, @swrobel

Did you patch react-navigation PR with #1029?
https://github.com/react-navigation/react-navigation/pull/9772

**Comment by swrobel** [comment]
> Did you patch react-navigation PR with #1029?
> [react-navigation/react-navigation#9772](https://github.com/react-navigation/react-navigation/pull/9772)

I did. It was a bit tricky to figure out how to do it in package.json, but this seemed to work for me:
`"@react-navigation/bottom-tabs": "https://gitpkg.now.sh/react-navigation/react-navigation/packages/bottom-tabs?@wolewicki/add-tabs-or-drawer-prop"`

**Comment by SimpleCreations** [comment]
@burakgormek no, but after having done that, the issue is gone as well. To clarify, I installed #1029 and [#9772 from react-navigation](https://github.com/react-navigation/react-navigation/pull/9772).

**Comment by SimpleCreations** [comment]
@swrobel this worked for me:

```
npm i "https://gitpkg.now.sh/react-navigation/react-navigation/packages/bottom-tabs?8cc35e349fa767a8b9c613f2ec28e8c5b0cd64ea
```

**Comment by WoLewicki** [comment]
I think it would be easiest to just change it in your `node_modules` for now. You can use [patch-package](https://www.npmjs.com/package/patch-package) if you want to have all those changes in the code. So I believe #1029 with the PR from `react-navigation` fixes the problem yeah? @SimpleCreations @swrobel

**Comment by SimpleCreations** [comment]
> So I believe #1029 with the PR from `react-navigation` fixes the problem yeah? @SimpleCreations @swrobel

Yes

**Comment by swrobel** [comment]
Not for me, although I will re-test & post a repro if I'm able to create one outside of my project.

**Comment by WoLewicki** [comment]
@swrobel keep in mind that it won't work if you have a `stack` navigator between the `native-stack`s, but we discourage nesting navigators of same kind one in another.

**Comment by swrobel** [comment]
> @swrobel keep in mind that it won't work if you have a `stack` navigator between the `native-stack`s, but we discourage nesting navigators of same kind one in another.

Do you mean a non-native stack navigator nested inside a native-stack? I don't have that setup, but I do have nested native-stack navigators.

**Comment by a-eid** [comment]
having a similar issue.

https://user-images.githubusercontent.com/19273413/128310978-94746ae9-6509-4802-b773-78297cda1310.mp4

**Comment by WoLewicki** [comment]
@a-eid it still happens after incorporating both PRs mentioned in https://github.com/software-mansion/react-native-screens/issues/619#issuecomment-888382535? @swrobel I meant the first scenario, so it should be fine. Please provide a repo with reproduction then, would be best if it already had the needed changes e.g. by using patch-package.

**Comment by a-eid** [comment]
@WoLewicki issue still happening with the latest release `3.7.0`.

**Comment by burakgormek** [comment]
@a-eid You have to patch react-navigation PR which is not merged yet.
https://github.com/react-navigation/react-navigation/pull/9772

**Comment by a-eid** [comment]
@burakgormek thanks alot, I confirm that patching react navigation has fixed the issue for me. 

cc @WoLewicki

**Comment by vesparny** [comment]
@a-eid how did you patch it?

**Comment by a-eid** [comment]
I only needed to patch the bottom tab lib, also you need to be using version 6.
